# Site settings
name: Dylan C McComas
email: wakaidev@gmail.com
#canonical_url: https://wakai.dev
keywords: 'Software Engineer, Python, Swift, TypeScript, MongoDB, Machine Learning, Deep Learning, Startups, Agile, Pair Programming'
skills: 'Senior Software Engineer in St. Petersburg, FL'
# baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  #  - title: linkedin
  #    url: https://www.linkedin.com/in/cgroom/
  #  - title: medium
  #    url: https://medium.com/@cgroom
  - title: twitter
    url: https://twitter.com/wakaidev

# Google webmaster tools
google_verify: google-site-verification=gd1Iw9Y8K3dlE73khkHvjQ1Eoh4jsPI8nQnS-7LONZs

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: '33, 150, 243'
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
